name: Test Api
on: [push, workflow_dispatch]

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/simple-node-api
        ports:
          - 3001:3000
        env:
          MONGO_HOSTNAME: mongo
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Dump Services Context
        run: echo "${{ toJson(job.services) }}"
      - name: Post a user
        run: |
          curl -sd '{"username":"hello","address":"world"}' -H 'Content-Type: application/json' http://localhost:3001/api/users
      - name: Get Users
        run: curl -s http://localhost:3001/api/users